server:
  port: 7002

#Eureka配置
eureka:
  client:
    service-url: # 配置eureka集群的其他成员
      defaultZone: http://127.0.0.1:7001/eureka
    fetch-registry: false # 不检索服务
    register-with-eureka: false # 自己本身就为服务注册中心就不需要注册自己
