server:
  port: 8001

mybatis:
  mapper-locations: classpath:mybatis/mapper/*.xml
  type-aliases-package: com.zou.pojo.*

spring:
  datasource:
    username: root
    password: 123456@Root
    url: jdbc:mysql://82.156.155.250:3306/db01_springcloud?useUnicode=true&characterEncoding=utf-8&serverTimezone=UTC
    driver-class-name: com.mysql.cj.jdbc.Driver